name: Pre-Commit Checks

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install pre-commit
        run: poetry run pip install pre-commit
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files
